version: "3.9"

services:
  message-broker:
    container_name: sparks-message-broker
    build: server
    image: sparks/message-broker-server:latest
    environment:
      - RABBITMQ_DEFAULT_USER=${ADMIN_USER}
      - RABBITMQ_DEFAULT_PASS=${ADMIN_PASS}
    volumes:
      - message-broker-data:/var/lib/rabbitmq
    ports:
      - ${BROKER_EXTERNAL_PORT}:5672
      - ${MANAGER_EXTERNAL_PORT}:15672
    networks:
      - sparks-network

volumes:
  message-broker-data:
    name: sparks-message-broker-data
