version: "3.9"

services:
  message-broker:
    container_name: sparks-message-broker
    build: server
    image: sparks/message-broker:latest
    environment:
      - RABBITMQ_DEFAULT_USER=${MESSAGE_BROKER_ADMIN_USER}
      - RABBITMQ_DEFAULT_PASS=${MESSAGE_BROKER_ADMIN_PASS}
    volumes:
      - message-broker-data:/var/lib/rabbitmq
    ports:
      - ${MESSAGE_BROKER_BROKER_EXTERNAL_PORT}:5672
      - ${MESSAGE_BROKER_MANAGER_EXTERNAL_PORT}:15672
    networks:
      - sparks-network

volumes:
  message-broker-data:
    name: sparks-message-broker-data
