version: "3.9"

services:
  discovery-server:
    container_name: sparks-discovery-server
    build: .
    image: sparks/discovery-server:latest
    restart: on-failure
    environment:
      - PORT=${DISCOVERY_SERVER_PORT}
      - CONFIG_SERVER_BASIC_AUTH_URL=${DISCOVERY_SERVER_CONFIG_SERVER_BASIC_AUTH_URL}
    depends_on:
      - config-server
    ports:
      - ${DISCOVERY_SERVER_EXTERNAL_PORT}:${DISCOVERY_SERVER_PORT}
    networks:
      - sparks-network
