version: "3.9"

services:
  discovery-server:
    container_name: sparks-discovery-server
    build: .
    image: sparks/discovery-server:latest
    restart: on-failure
    environment:
      - PORT=${PORT}
      - CONFIG_SERVER_BASIC_AUTH_URL=${CONFIG_SERVER_BASIC_AUTH_URL}
    depends_on:
      - config-server
    ports:
      - ${EXTERNAL_PORT}:${PORT}
    networks:
      - sparks-network
