server:
  port: ${PORT}

spring:
  cloud:
    config:
      server:
        git:
          uri: ${REPOSITORY_URL}
          clone-on-start: true
  security:
    user:
      name: ${DEFAULT_USERNAME}
      password: ${DEFAULT_PASSWORD}
