version: "3.9"

services:
  config-server:
    container_name: sparks-config-server
    build: .
    image: sparks/config-server:latest
    environment:
      - PORT=${CONFIG_SERVER_PORT}
      - REPOSITORY_URL=${CONFIG_SERVER_REPOSITORY_URL}
      - DEFAULT_USERNAME=${CONFIG_SERVER_DEFAULT_USERNAME}
      - DEFAULT_PASSWORD=${CONFIG_SERVER_DEFAULT_PASSWORD}
    ports:
      - ${CONFIG_SERVER_EXTERNAL_PORT}:${CONFIG_SERVER_PORT}
    networks:
      - sparks-network
